name: Module CI Checks (Lab 4)

on:
  # Run on pushes to main branch
  push:
    branches:
      - main
  # Run on pull requests targeting main branch
  pull_request:
    branches:
      - main
  # Allows manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  test:
    name: Lint, Validate, Test, Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: "1.7.x" # Optional: Pin version

      - name: Terraform Format Check
        working-directory: ./lab4 # Run commands relative to lab4 dir
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./lab4
        run: terraform init

      - name: Terraform Validate
        working-directory: ./lab4
        run: terraform validate

      - name: Terraform Test Module
        working-directory: ./lab4
        run: terraform test -filter=modules/sqs-secure/tests/sqs_secure_test.tftest.hcl

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov Scan
        working-directory: ./lab4 # Checkov runs from here
        run: checkov -d ./modules/sqs-secure --quiet # Scan only module code